version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=kamrul
      - MONGO_PASSWORD=hasan
      - SESSION_SECRET=secret
    # env_file:
    #   - ./.env
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kamrul
      - MONGO_INITDB_ROOT_PASSWORD=hasan
